FROM fedora:27

LABEL maintainer="Thomas Brown <tabsoftwareconsulting@gmail.com>"

RUN dnf -y update && dnf -y install \
    boost-devel \
    boost-build \
    cmake \
    doxygen \
    gcc \
    gcc-c++ \
    graphviz \
    make \
    pkg-config

#RUN groupadd -g 10000 jenkins
RUN groupadd -g 117 jenkins
#RUN useradd -u 10000 -g jenkins jenkins
RUN useradd -u 113 -g jenkins jenkins

# restore user
USER jenkins

ENV HOME /home/jenkins

WORKDIR /home/jenkins

# set up Boost.Build
RUN echo "# DO NOT EDIT - generated by Dockerfile" > "${HOME}/user-config.jam"
RUN echo "using doxygen ;" >> "${HOME}/user-config.jam"
RUN echo "using gcc ;" >> "${HOME}/user-config.jam"
RUN echo "using clang ;" >> "${HOME}/user-config.jam"
RUN echo "using boost : \"\" : <include>/usr/include <library>/usr/lib <layout>system ;" >> "${HOME}/user-config.jam"

# @todo the contrib/boost.jam file is missing from the installation on
# the underlying Docker (Debian Stretch), so add it
COPY boost.jam "${HOME}"
