FROM tee3/jenkinsci-slave:0.0.1

LABEL maintainer="Thomas Brown <tabsoftwareconsulting@gmail.com>"

USER root

RUN dnf -y update && dnf -y install \
    boost-devel \
    boost-build \
    cmake \
    doxygen \
    gcc \
    gcc-c++ \
    graphviz \
    make \
    pkg-config

USER jenkins

# set up Boost.Build
RUN echo "# DO NOT EDIT - generated by Dockerfile" > "${HOME}/user-config.jam"
RUN echo "using doxygen ;" >> "${HOME}/user-config.jam"
RUN echo "using gcc ;" >> "${HOME}/user-config.jam"
RUN echo "using clang ;" >> "${HOME}/user-config.jam"
RUN echo "using boost : \"\" : <include>/usr/include <library>/usr/lib <layout>system ;" >> "${HOME}/user-config.jam"

# @todo the contrib/boost.jam file is missing from the installation on
# the underlying Docker (Debian Stretch), so add it
COPY boost.jam "${HOME}"
